gwkokab/gwkokab

README.md, jaxtro/models/wysocki2019massmodel.py, tests/wysocki2019massmodel_test.py
=> `Wysocki2019MassModel` random realization method signature not aligned with JAXampmler

gwkokab/_src/models/models.py, gwkokab/_src/models/utils/transformations.py, gwkokab/models/transformations.py
=> Convert primary mass and mass ratio to component masses

.pre-commit-config.yaml, gwkokab/_src/models/models.py
=> Smoothing model attribute access failure resolved

gwkokab/_src/models/transformations.py
=> Transformation Jacobians fixed

.github/workflows/update_all_top_ranking_issues.yml
=> Update top ranking issue once a week

src/gwkokab/_src/models/constraints.py
=> gh-265: constraint name typo fixed

docs/source/gwkokab.models.rst, src/gwkokab/models/_models.py, src/gwkokab/models/constraints.py, src/gwkokab/models/transformations.py, tests/test_constraints.py, tests/test_model_transformations.py
=> gh-272: depreciating unique_interval constraint

src/gwkokab/models/_models.py, src/gwkokab/models/constraints.py, src/gwkokab/models/utils.py
I don't think https://github.com/pyro-ppl/numpyro/issues/1864 would solve our problem therefore we are moving the conlusion
=> Functional use of relevant methods of `DoublyTruncatedPowerLaw` by `NumPyro`

src/gwkokab/models/_models.py, tests/test_distributions.py
=> gh-275: Different PRNGKeys for different random variates

src/gwkokab/models/_models.py, src/gwkokab/models/transformations.py, src/gwkokab/utils/transformations.py
=> gh-263: Handling limiting cases in PowerLawPrimaryMassRatio

src/gwkokab_scripts/corner_plot.py, src/kokab/ecc_matters/genie.py, src/kokab/powerlawpeak/genie.py, src/kokab/single_gaussians/genie.py, src/kokab/utils/genie_parser.py
=> gh-260: Required removed from default values in genie and sage scripts

src/kokab/utils/common.py, src/kokab/utils/genie_parser.py, src/kokab/utils/sage_parser.py, tests/kokab/utils/test_common.py
=> gh-298: Raise error if data files are unavailable

src/gwkokab/inference/bake.py, src/gwkokab/inference/poissonlikelihood.py, src/kokab/utils/regex.py, tests/kokab/utils/test_regex.py
=> gh-287: Duplication of parameters in inference

.pre-commit-config.yaml, CHANGELOG.md, pyproject.toml, src/gwkokab/debug/_debug.py, src/gwkokab/inference/bake.py, src/gwkokab/inference/poissonlikelihood.py, src/gwkokab/inference/utils.py, src/gwkokab/models/_models.py, src/gwkokab/models/constraints.py, src/gwkokab/models/wrappers.py, src/gwkokab/population/_factory.py, src/gwkokab/vts/_neuralvt.py, src/gwkokab_scripts/ppd_plot.py, src/kokab/n_pls_m_gs/common.py, src/kokab/utils/common.py, src/kokab/utils/genie_parser.py, src/kokab/utils/ppd.py, src/kokab/utils/ppd_parser.py, src/kokab/utils/sage_parser.py
=> gh-320: docs and docstrings formatted

docs/source/gwkokab.models.rst, src/gwkokab/inference/poissonlikelihood.py, src/gwkokab/models/_models.py, src/gwkokab/models/utils.py, src/kokab/n_pls_m_gs/ppd.py, src/kokab/n_pls_m_gs/sage.py, tests/test_distributions.py, tests/test_distributions_mixture.py
=> gh-322: Implementation of `ScaledMixture` and relevant refactoring

CHANGELOG.md, src/kokab/ecc_matters/genie.py, src/kokab/ecc_matters/sage.py, src/kokab/powerlawprimarymassratio/genie.py, src/kokab/powerlawprimarymassratio/sage.py, src/kokab/single_gaussians/genie.py
=> gh-330: deprecation of special cases of `n_pls_m_gs`

src/kokab/n_pls_m_gs/common.py, src/kokab/n_pls_m_gs/genie.py, src/kokab/n_pls_m_gs/sage.py, src/kokab/utils/common.py, src/kokab/utils/genie_parser.py, src/kokab/utils/sage_parser.py
=> gh-328: variable parameters for VT

src/gwkokab/models/utils.py, src/gwkokab/population/_factory.py, src/gwkokab_scripts/scatter2d.py
This feature includes the storing of indices of multi-rate population, that are later used assign them different colors in the plots.
=> refactor: `PopulationFactory` for different color plots for sub-population

src/gwkokab/inference/poissonlikelihood.py, src/gwkokab/population/_factory.py
=> refactor(gh-360): remove scale_factor from `PoissonLikelihood` and `PopulationFactory`

src/gwkokab/inference/flowMChandler.py, src/kokab/chi_eff_q_relation/sage.py, src/kokab/ecc_matters/sage.py, src/kokab/n_pls_m_gs/sage.py, src/kokab/n_spls_m_sgs/sage.py, src/kokab/utils/sage_parser.py
=> feat(gh-403): debug nans flag in sage script

src/gwkokab/models/nsmoothedpowerlawmsmoothedgaussian/_model.py, src/gwkokab/models/utils/__init__.py, src/gwkokab/models/utils/_ncombination.py, src/kokab/n_spls_m_sgs/ppd.py, src/kokab/n_spls_m_sgs/sage.py
All analyses in GWKokab are performed using carefully chosen parameters; in the case of masses, they are primary and secondary mass components. Models in primary mass and mass ratio are transformed into primary and secondary mass components. For previously defined cases the ppd plot are made in their raw parameters. This PR provides features to make ppd in raw parameters.
=> feat: introduce raw versions of smoothed powerlaws and gaussians

pyproject.toml, src/cli_gwkokab/r_hat_plot.py
```bash
gwk_r_hat_plot \
--chains-regex "sampler_data/prod_chains_*.dat" \
--output $dir/r_hat.png \
--label "alpha_pl_0" "mmax_pl_0" "mmin_pl_0" "ecc_scale_pl_0" "log_rate_0"
```
=> feat: cli for creating Pearson correlation coefficient plots for chains

src/gwkokab/inference/utils.py
=> feat(gh-377): different numbers of loops for training and production

src/gwkokab/inference/bake.py, src/gwkokab/inference/poissonlikelihood.py, src/gwkokab/models/_models.py, src/gwkokab/models/utils/_joindistribution.py, src/gwkokab/poisson_mean/_abc.py, src/gwkokab/vts/_popmodelvt.py, src/kokab/one_powerlaw_one_peak/poisson_mean.py
=> fix: sort hashable and unhashable types into static and non-static fields

src/gwkokab/models/constraints.py, src/gwkokab/models/npowerlawmgaussian/_model.py, src/gwkokab/models/utils/_joindistribution.py, src/gwkokab/poisson_mean/_importance_sampling.py, src/gwkokab/poisson_mean/_inverse_transform_sampling.py, tests/gwkokab/poisson_mean/conftest.py, tests/gwkokab/poisson_mean/test_importance_sampling.py, tests/gwkokab/poisson_mean/test_inverse_transform_sampling.py, tests/test_constraints.py
=> tests(gh-438): unit tests for Poisson rate estimates

src/cli_gwkokab/batch_scatter2d.py, src/cli_gwkokab/batch_scatter3d.py, src/cli_gwkokab/chain_plot.py, src/cli_gwkokab/corner_plot.py, src/cli_gwkokab/ess_plot.py, src/cli_gwkokab/joint_plot.py, src/cli_gwkokab/ppd_plot.py, src/cli_gwkokab/r_hat_plot.py, src/cli_gwkokab/scatter2d.py, src/cli_gwkokab/scatter3d.py
This PR contains following updates,
=> feat: update matplotlib configuration for LaTeX rendering

src/gwkokab/inference/flowMChandler.py, src/gwkokab/models/npowerlawmgaussian/_model.py, src/gwkokab/models/nsmoothedpowerlawmsmoothedgaussian/_model.py, src/gwkokab/models/utils/_joindistribution.py, src/gwkokab/models/utils/_scaledmixture.py, src/gwkokab/poisson_mean.py, src/kokab/chi_eff_q_relation/sage.py, src/kokab/ecc_matters/sage.py, src/kokab/n_pls_m_gs/sage.py, src/kokab/n_spls_m_sgs/sage.py, src/kokab/one_powerlaw_one_peak/sage.py
Reimplemented the `ScaledMixture` utility to remove dependency from `MixtureGeneral`.
=> refactor: reimplemented `ScaledMixture` utility

src/cli_gwkokab/batch_scatter2d.py, src/cli_gwkokab/batch_scatter3d.py, src/cli_gwkokab/chain_plot.py, src/cli_gwkokab/corner_plot.py, src/cli_gwkokab/ess_plot.py, src/cli_gwkokab/joint_plot.py, src/cli_gwkokab/ppd_plot.py, src/cli_gwkokab/r_hat_plot.py, src/cli_gwkokab/scatter2d.py, src/cli_gwkokab/scatter3d.py
On some remote work machines latex is not available, therefore making latex font optional.
=> feat: add option to use LaTeX for rendering text in plotting scripts

src/kokab/chi_eff_q_relation/sage.py, src/kokab/ecc_matters/sage.py, src/kokab/n_pls_m_gs/sage.py, src/kokab/n_spls_m_sgs/sage.py, src/kokab/one_powerlaw_one_peak/sage.py
Checking if the provided data columns and parameters are the same.
=> feat(gh-319): add parameter validation to ensure consistency in posterior data across models

.github/workflows/ci.yml
Enables CI workflow to run on `dev` branch.
=> feat: update CI workflow to trigger on dev branch and additional pull request types

src/gwkokab/vts/_utils.py, src/kokab/chi_eff_q_relation/sage.py, src/kokab/ecc_matters/sage.py, src/kokab/n_pls_m_gs/sage.py, src/kokab/n_spls_m_sgs/sage.py, src/kokab/one_powerlaw_one_peak/sage.py, src/kokab/utils/common.py
Directly transferring arrays to the device. This improvement reduced the compilation time by 5x (empirically).
Related to #454
=> feat(gh-454): optimize data handling by utilizing `jax.device_put`

src/gwkokab/cosmology/_cosmology.py
Changing `gwkokab.Cosmology` to subclass of `equinox.Module` to be treated as a `PyTree` and a dataclass.
=> refactor: update `Cosmology` class to use `equinox.Module` to be treated as `PyTree`

.github/PULL_REQUEST_TEMPLATE.md, pyproject.toml, src/kokab/chi_eff_q_relation/sage.py, src/kokab/ecc_matters/sage.py, src/kokab/n_pls_m_gs/sage.py, src/kokab/n_spls_m_sgs/sage.py, src/kokab/one_powerlaw_one_peak/sage.py, src/kokab/utils/flowMC_helper.py, src/kokab/utils/sage_parser.py
We often encounter memory-related bugs. This flag can help us debug some aspect of it.
- #480
=> feat(gh-480): add memory leak checking option to sage scripts

pyproject.toml, src/kokab/ecc_matters/ppd.py
PPD plot generation script for eccentricity matters analysis
=> feat: add PPD script for eccentricity matters model

src/kokab/ecc_matters/ppd.py, src/kokab/n_pls_m_gs/ppd.py, src/kokab/n_spls_m_sgs/ppd.py, src/kokab/one_powerlaw_one_peak/ppd.py, src/kokab/utils/flowMC_helper.py, src/kokab/utils/ppd_parser.py
Weighting final samples by nf model.
=> feat: option for sample generation with weighted sampling in flowMC helper

src/cli_gwkokab/ppd_plot.py
* Added new arguments for median and PPD line colors, alpha values, and linestyle options.
* Grouped related arguments under a "Pretty Options" section for better organization.
* Updated plotting logic to utilize new customizable parameters for improved visual representation.
=> feat: enhance PPD plotting options with additional customization parameters

.github/workflows/ci.yml, README.md, docs/requirements.txt, pyproject.toml
Integrating coveralls for test suite coverage.
=> chore(ci): update CI workflow to enhance testing and coverage reporting 

src/kokab/n_pls_m_gs/genie.py, src/kokab/n_pls_m_gs/sage.py, src/kokab/n_spls_m_sgs/sage.py
Replacing the flags like `--no-spin` to `--add-spin`, along with relevant changes.
=> refactor: update argument flags to use positive flags to include spin, tilt, eccentricity, and redshift parameters in the model

src/kokab/n_pls_m_gs/genie.py
Stratifying error parameters by their inclusion.
=> chore: stratify error params by their inclusion

src/kokab/n_pls_m_gs/ppd.py, src/kokab/n_spls_m_sgs/ppd.py
Generate PPD for every component of multi source models.
=> refactor: add per-component option for multi source model PPD computation

src/cli_gwkokab/ppd_plot.py
Create multiple PPDs in a single plot.
=> refactor: update PPD plotting to handle multiple data sources

.pre-commit-config.yaml, src/kokab/n_pls_m_gs/genie.py, src/kokab/n_pls_m_gs/sage.py, src/kokab/n_spls_m_sgs/sage.py
Rename the CLI args to be more bespoke in terms of their functionality.
=> refactor: update spin parameter handling in `n_pls_m_gs` and `n_spls_m_sgs` modules

src/gwkokab/inference/poissonlikelihood.py, src/gwkokab/models/transformations.py, src/gwkokab/models/utils/_scaledmixture.py, src/gwkokab/poisson_mean.py, uv.lock
Corrected the single event likelihood.
=> fix: correction of single event likelihood calculation

src/kokab/utils/flowMC_helper.py
Samples according to the effective sample size from normalizing flows.
=> fix: update sampling logic to handle calculate effective sample size and weight samples

src/gwkokab/vts/_train.py
Plotting the loss of complete data set with quantiles.
=> refactor: add total loss plotting to `train_regressor` function

src/kokab/ecc_matters/sage.py, src/kokab/n_pls_m_gs/sage.py, src/kokab/n_spls_m_sgs/sage.py, src/kokab/one_powerlaw_one_peak/sage.py, src/kokab/utils/common.py
Read the reference prior from the injection files and use it in the inference.
=> refactor(sage): introduce logic to handle reading and use of log reference prior in sage

src/gwkokab/inference/jenks.py, src/gwkokab/inference/poissonlikelihood.py, src/gwkokab/models/nsmoothedpowerlawmsmoothedgaussian/_model.py, src/gwkokab/models/redshift/_models.py, src/gwkokab/poisson_mean.py, src/gwkokab/utils/tools.py, src/gwkokab/vts/_realinjvt.py, src/kokab/one_powerlaw_one_peak/ppd.py, src/kokab/one_powerlaw_one_peak/sage.py, src/kokab/utils/flowMC_helper.py
We have added a default spin model and an isotropic tilt model.
- #454
=> refactor(gh-135, gh-454): add default spin and isotropic cos tilt and memory scalling enhancement

src/gwkokab/models/constraints.py, src/gwkokab/models/npowerlawmgaussian/_model.py, src/gwkokab/models/nsmoothedpowerlawmsmoothedgaussian/_model.py, src/gwkokab/models/utils/__init__.py, src/gwkokab/models/utils/_extendedsupporttransformeddistribution.py, src/gwkokab/models/utils/_ncombination.py, src/kokab/one_powerlaw_one_peak/ppd.py
This PR is a solution to mentioned issues.
- https://github.com/pyro-ppl/numpyro/issues/1989
- https://github.com/pyro-ppl/numpyro/issues/2043
=> feat: `ExtendedSupportTransformedDistribution` extension of `TransformedDistribution`

src/cli_gwkokab/chain_plot.py
- Removed the `--dimension` flag.
- Add option to plot 90%, 50% and mean of the chains instead of every chain.
=> feat(cli_gwkokab): add band (confidence interval) plotting option to chain plot script

src/kokab/utils/flowMC_based.py
`flowMC` has restricted access to some parameters via its bundle API; we have copied and modified it with full access to all parameters.
=> feat: exposing all parameters for tuning in `flowMC` bundle API

CITATION.bib, README.md
GWKokab's paper is available on arXiv. Updating citation!
=> chore: update citation to arxiv pre-print

src/kokab/__init__.py, src/kokab/ecc_matters/f_monk.py, src/kokab/ecc_matters/genie.py, src/kokab/n_pls_m_gs/f_monk.py, src/kokab/n_pls_m_gs/genie.py, src/kokab/n_pls_m_gs/sage.py, src/kokab/one_powerlaw_one_peak/sage.py, src/kokab/utils/logger.py
Rerouting the logging into a log file at a designated location instead of the terminal.
- closes #614
=> refactor(gh-614): logging into a log file
