- src/gwkokab/models/redshift/_models.py
Under the following, `numpyro.distributions.utils.is_prng_key` is removed.
- https://github.com/pyro-ppl/numpyro/pull/1642
> refactor: remove deprecated `is_prng_key`

- makefile
- src/kokab/utils/common.py
- src/kokab/utils/priors.py
Formally we were providing priors as a list of two elements where the value at index 0 is low and the value at index 1 is high. It has restricted us to uniform priors. Now we can provide priors in the following format allowing a broader category of priors to be passed.
```json
{
"log_rate_0": { "dist": "Uniform", "low": -3.0, "high": 10.0 },
"log_rate_1": "log_rate_0",
"alpha_pl_0": { "dist": "Uniform", "low": -4.0, "high": 12.0 },
"beta_pl_0": { "dist": "Uniform", "low": -2.0, "high": 7.0 },
"mmin_pl_0": { "dist": "Uniform", "low": 2.0, "high": 10.0 },
"mmax_pl_0": { "dist": "Uniform", "low": 30.0, "high": 100.0 },
"delta_pl_0": { "dist": "Uniform", "low": 0, "high": 10 },
"loc_g_0": { "dist": "Uniform", "low": 20, "high": 50 },
"scale_g_0": { "dist": "Uniform", "low": 1, "high": 10 }, …
```
> feat: API for non-uniform priors in JSON file

- src/gwkokab/models/_models.py
- src/kokab/one_powerlaw_one_peak/common.py
- src/kokab/one_powerlaw_one_peak/sage.py
- tests/test_distributions.py
Implemented the normalization of `PowerlawAndPeakModel` same as the Model-C of GWTC-1 paper [^1]. We have carefully considered smoothing regions and picked samples from there.
[^1]: [Binary Black Hole Population Properties Inferred from the First and Second Observing Runs of Advanced LIGO and Advanced Virgo](https://dx.doi.org/10.3847/2041-8213/ab3800)
> feat: mixture distributions for powerlaw and gaussian sampling in `SmoothedPowerlawAndPeak` model for normalization

- .github/workflows/ci.yml
We have added readthedoc webhook to eye on the build status of documentation after which we do not require the removed step.
> chore(ci): remove documentation rendering step from CI workflow

- src/gwkokab/inference/poissonlikelihood.py
After troublesome attempts to handle `jnp.nans` manually, we have surrendered to converting them to `-jnp.inf`.
> fix: handle NaN and infinite values in log posterior calculation

- pyproject.toml
- src/gwkokab/models/_models.py
Using a fixed grid with less dimension to compute normalization constants of the smoothing mass model offers a great trade-off in optimization while compromising less on accuracy.
> feat: use fix grid of primary mass and mass ratio to compute normalization constants

- src/gwkokab/vts/_abc.py
- src/gwkokab/vts/_neuralvt.py
- src/gwkokab/vts/_popmodelvt.py
- src/kokab/chi_eff_q_relation/sage.py
- src/kokab/ecc_matters/genie.py
- src/kokab/ecc_matters/sage.py
- src/kokab/n_pls_m_gs/genie.py
- src/kokab/n_pls_m_gs/sage.py
- src/kokab/n_spls_m_sgs/sage.py
- src/kokab/one_powerlaw_one_peak/sage.py
We have used `jax.lax.map` to vectorize the logVT function to reduce the memory footprint. We have not provided any `batch_size` yet to see the effect of sequential execution of loops.
> refactor(gh-451): replace `jax.vmap` with `jax.lax.map` for logVT function in neural and population models

- src/gwkokab/inference/flowMChandler.py
- src/kokab/chi_eff_q_relation/sage.py
- src/kokab/ecc_matters/sage.py
- src/kokab/n_pls_m_gs/sage.py
- src/kokab/n_spls_m_sgs/sage.py
- src/kokab/one_powerlaw_one_peak/sage.py
- src/kokab/utils/sage_parser.py
This PR contains the feature of profiling device memory. When enabled it will create a file with the name `gwkokab_memory_*.prof`, which can be viewed using pprof tools. For details see [JAX - Profiling device memory](https://docs.jax.dev/en/latest/device_memory_profiling.html).
> feat(gh-440): add memory profiling option to `flowMChandler.run` method

- src/cli_gwkokab/batch_scatter2d.py
- src/cli_gwkokab/batch_scatter3d.py
- src/cli_gwkokab/chain_plot.py
- src/cli_gwkokab/corner_plot.py
- src/cli_gwkokab/ess_plot.py
- src/cli_gwkokab/joint_plot.py
- src/cli_gwkokab/ppd_plot.py
- src/cli_gwkokab/r_hat_plot.py
- src/cli_gwkokab/scatter2d.py
- src/cli_gwkokab/scatter3d.py
Many work machines do not have special fonts. This PR avoids being too fancy.
> refactor: remove redundant font setting from plotting scripts

- src/kokab/n_pls_m_gs/ppd.py
- src/kokab/n_spls_m_sgs/ppd.py
- src/kokab/one_powerlaw_one_peak/ppd.py
- src/kokab/utils/common.py
- src/kokab/utils/ppd.py
We have to handle the special case of batched models only to generate ppd. We can simplify their implementation if we do sequential generation of ppd instead of vmaped.
Closes #460
> refactor(gh-460): Serializing ppd generation to avoid batched models

- src/gwkokab/models/_models.py
- src/gwkokab/models/multivariate/_chi_eff_mass_ratio.py
We were missing some attributes in `pytree_data_field`, causing `tests/test_distributions.py::test_dist_pytree` were failing.
> fix: expand `pytree_data_fields` in distribution models for improved pytree flattening

- pyproject.toml
A recent update (https://github.com/kazewong/flowMC/pull/189) in flowMC has many breaking changes. It is said to be released in the upcoming weeks (ref: https://github.com/kazewong/flowMC/pull/185#issuecomment-2676215357). We are constraining the version to the latest one and will later deal with the new breaking changes coming with flowMC.
> chore(deps): pin flowMC dependency to version 0.3.4

- src/gwkokab/models/__init__.py
- src/gwkokab/models/nsmoothedpowerlawmsmoothedgaussian/__init__.py
- src/gwkokab/models/nsmoothedpowerlawmsmoothedgaussian/_model.py
- src/gwkokab/models/utils/_joindistribution.py
- src/gwkokab/vts/_neuralvt.py
- src/gwkokab/vts/_popmodelvt.py
- src/kokab/chi_eff_q_relation/sage.py
- src/kokab/ecc_matters/sage.py
- src/kokab/n_pls_m_gs/sage.py
- src/kokab/n_spls_m_sgs/sage.py
- src/kokab/one_powerlaw_one_peak/ppd.py
- src/kokab/one_powerlaw_one_peak/sage.py
- src/kokab/utils/common.py
- src/kokab/utils/ppd.py
This PR introduces the required redshift model in Single Powerlaw and Peak.
- #135
GWTC-3 paper analyzes Single powerlaw and peak, which is incomplete without the joining powerlaw redshift model. We have created a separate implementation for this model named `SmoothedPowerlawPeakAndPowerlawRedshift`, with hardcoded Plank 2015 Cosmology.
> feat(gh-135): extends `SmoothedPowerlawAndPeak` with `PowerlawRedshift`

- src/kokab/chi_eff_q_relation/sage.py
- src/kokab/ecc_matters/genie.py
- src/kokab/ecc_matters/sage.py
- src/kokab/n_pls_m_gs/genie.py
- src/kokab/n_pls_m_gs/sage.py
- src/kokab/n_spls_m_sgs/sage.py
- src/kokab/one_powerlaw_one_peak/sage.py
- src/kokab/utils/common.py
- src/kokab/utils/genie_parser.py
- src/kokab/utils/sage_parser.py
Remove `--vt-path` argument for the sage and genie parser, now it will be provided in the `vt.json`
> refactor: redundant `vt-path` argument from VT options in parsers

- docs/source/conf.py
- pyproject.toml
- ruff.toml
- src/cli_gwkokab/ppd_plot.py
- src/gwkokab/models/_models.py
- src/gwkokab/models/npowerlawmgaussian/_model.py
- src/gwkokab/models/nsmoothedpowerlawmsmoothedgaussian/_model.py
- src/gwkokab/models/utils/_joindistribution.py
- src/gwkokab/models/utils/_ncombination.py
- src/gwkokab/models/utils/_scaledmixture.py
- src/gwkokab/utils/math.py
- src/gwkokab/utils/tools.py
- tests/test_distributions_mixture.py
Remove the extra dependency of `typing_extensions` and refactor the dependent code.
> refactor: replace `typing_extensions` imports with standard `typing` imports

- makefile
- pyproject.toml
Add platform-specific installation of JAX available in `pyproject.toml`.
- closes #481
We have added support to install platform-specific JAX. Before this, we had to install them separately, occasionally affecting the dependency resolution. Now we can install by specifying `gwkokab[cuda12]` or `gwkokab[tpu]` or `gwkokab` to install for cuda capable GPU, Google TPUs, or CPU respectively. For developer `make install PLATFORM=...`, where `...` will be replaced by the `cuda12` or `tpu` and for CPU based installation `make install` will work.
> chore(gh-481): add CUDA/TPU platform support in installation

- makefile
- pyproject.toml
Dependency resolution failed due to `jax[tpu]`. As we most of the time use GPUs, therefore we are disabling TPU based JAX dependency installation, to debug later.
- #481
> chore(gh-481): disable TPU support in `pyproject.toml`

- src/kokab/ecc_matters/common.py
- src/kokab/ecc_matters/ppd.py
- src/kokab/n_pls_m_gs/ppd.py
- src/kokab/n_spls_m_sgs/ppd.py
- src/kokab/one_powerlaw_one_peak/ppd.py
- src/kokab/utils/common.py
- src/kokab/utils/ppd_parser.py
With this update, we can pass ranges in the PPD generation script by the name of parameters without any order like `--range name min max step`.
> refactor: enhance PPD range handling with parameter-specific range conversion

- src/kokab/utils/ppd.py
We were facing memory exhaustion errors,
```bash
numpy._core._exceptions._ArrayMemoryError: Unable to allocate 2.33 TiB for an array with shape (200, 200, 200, 200, 200) and data type float64
```
We were making and storing a mesh grid, which is manageable for 1-3 dimensions, but after that, the memory space required to store all this mesh grid goes out of bounds. Therefore, we are not creating meshgrids but iterating over them, which is a little inefficient, but it saves us from the above-mentioned memory errors.
- #460
> refactor(gh-460): optimize PPD computation with itertools product and simplified mesh generation

- src/kokab/ecc_matters/ppd.py
- src/kokab/n_pls_m_gs/ppd.py
- src/kokab/n_spls_m_sgs/ppd.py
- src/kokab/one_powerlaw_one_peak/ppd.py
- src/kokab/utils/ppd.py
- src/kokab/utils/ppd_parser.py
We have reverted the use of multithreading for ppd generation and returned to JAX-based methods, because they are fast.
- #461
- #478
Multithreading took enormous time, even days to compute simple and small grid size PPDs. It was better for us to use JAX-based method with little tweaks in memory consumptions.
> revert(gh-478): ppd generation previous method using `jax.lax.map` and `jax.vmap`

- makefile
- pyproject.toml
- uv.lock
We have added the index URL for JAX in pyproject to be used by uv by default.
- #481
> refactor(gh-481): index URL for JAX in `pyproject.toml`

- src/gwkokab/poisson_mean.py
- tests/gwkokab/test_poisson_mean.py
> refactor: rename 'scale' to 'time_scale' in PoissonMean class and tests

- src/kokab/utils/genie_parser.py
- src/kokab/utils/ppd_parser.py
- src/kokab/utils/sage_parser.py
We have set an unofficial nomenclature for files. We could set it as the default and make those arguments official, reducing the arguments passed in the CLI.
- closes #516
> refactor(gh-516): change required arguments to default values in parser functions

- src/gwkokab/models/constraints.py
It arose because all distributions were single variates, and the `jnp.concatenate` concatenated them one after another instead of expanding the dims and concatenating them. This PR fixes this issue.
- Fixes #553
> fix(gh-553): max `ndims` of a costraint is `prototype.ndim`

- src/gwkokab/errors.py
Fixed the mask initialization in `truncated_normal_error`, which was causing infinite while loops.
> fix: mask initialization in `truncated_normal_error` function

- src/gwkokab/models/__init__.py
- src/gwkokab/models/redshift/__init__.py
- src/gwkokab/models/redshift/_models.py
- tests/test_distributions.py
Implementation of a simple powerlaw to describe redshift models.
- #135 
`PowerlawRedshift` uses comoving volume in its definition, `SimpleRedshiftPowerlaw` is same thing but without comoving volume written purely using numpyro transforms and distributions.
> feat(gh-135): add `SimpleRedshiftPowerlaw` distribution

- src/gwkokab/poisson_mean.py
- src/gwkokab/vts/_abc.py
- src/gwkokab/vts/_neuralpdet.py
- src/gwkokab/vts/_neuralvt.py
- src/gwkokab/vts/_popmodelvt.py
- src/gwkokab/vts/_realinjvt.py
- src/gwkokab/vts/_semianalyticalinjvt.py
- src/gwkokab/vts/_syninjvt.py
Removing `init=False` as per the warning from equinox, patrick-kidger/equinox@f88e62ab809140334c2f987ed13eff0d80b8be13.
> fix: remove `init=False` from fields in various classes

- src/gwkokab/vts/_semianalyticalinjvt.py
> fix: add optional `ifar_pipelines` parameter to specify pipelines for ifar selection in semianalytical injections

- .github/workflows/ci.yml
Enable Python 3.12 and Python 3.13 in CI.
> fix: enable Python 3.12 and 3.13 in CI workflow
